name: Echo 
on:
  pull_request:
  check_run:
    types: 
    - rerequested
    - requested_action
  check_suite:
    types:
    - rerequested
jobs:
  test:
    runs-on: ubuntu-latest
    name: Dummy Echo
    steps:
      - name: Echo Variables
        run: |
          echo "WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "RUN ID: ${GITHUB_RUN_ID}"
          echo "RUN # : ${GITHUB_RUN_NUMBER}"
